const ICONS={home:'<svg viewBox="0 0 24 24"><path d="m3 10 9-7 9 7v10H4Z"/></svg>',book:'<svg viewBox="0 0 24 24"><path d="M4 5a2 2 0 0 1 2-2h12v17H6a2 2 0 0 0-2 2Zm0 0v15a2 2 0 0 1 2-2h12"/></svg>',test:'<svg viewBox="0 0 24 24"><path d="M6 3h12a2 2 0 0 1 2 2v14H6a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2Zm3 5h6M9 12h6M9 16h4"/></svg>',heart:'<svg viewBox="0 0 24 24"><path d="M20.8 8.9c0 5.5-8.8 10.1-8.8 10.1S3.2 14.4 3.2 8.9A4.7 4.7 0 0 1 12 6.1a4.7 4.7 0 0 1 8.8 2.8Z"/></svg>',user:'<svg viewBox="0 0 24 24"><circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/></svg>',settings:'<svg viewBox="0 0 24 24"><path d="M12 15.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7Z"/></svg>',search:'<svg viewBox="0 0 24 24"><circle cx="10.8" cy="10.8" r="6.8"/><path d="m16 16 5 5"/></svg>',sun:'<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M2 12h2M20 12h2"/></svg>',moon:'<svg viewBox="0 0 24 24"><path d="M20.5 14.2A8.5 8.5 0 0 1 9.8 3.5 8.5 8.5 0 1 0 20.5 14.2Z"/></svg>',play:'<svg viewBox="0 0 24 24"><path d="m8 5 11 7-11 7Z"/></svg>',back:'<svg viewBox="0 0 24 24"><path d="m15 18-6-6 6-6"/></svg>'};
const NAV=[['dashboard','Dashboard','home'],['subjects','Fanlar','book'],['books','Elektron kitoblar','book'],['tests','Testlar','test'],['favorites','Saqlanganlar','heart'],['profile','Profil','user'],['settings','Sozlamalar','settings']];
const subjects=[['anatomy','Anatomiya',72,38],['physiology','Fiziologiya',61,31],['histology','Gistologiya',44,26],['biochem','Biokimyo',55,29],['pharma','Farmakologiya',28,42],['pathology','Patologiya',36,34],['micro','Mikrobiologiya',19,25],['internal','Ichki kasalliklar',12,51],['surgery','Jarrohlik',8,37]].map(([id,name,p,m])=>({id,name,progress:p,materials:m}));
const books=[['guyton','Tibbiy fiziologiya asoslari','J. E. Hall','Fiziologiya',1176,64],['gray','Klinik anatomiya','S. Standring','Anatomiya',1584,31],['robbins','Robbins patologiya asoslari','V. Kumar','Patologiya',960,18],['lehninger','Biokimyo asoslari','D. Nelson','Biokimyo',1328,0],['lippincott','Farmakologiya vizual qo‘llanmasi','Katzung','Farmakologiya',512,46],['histology','Gistologiya: atlas','L. Gartner','Gistologiya',384,73],['micro','Tibbiy mikrobiologiya','Murray','Mikrobiologiya',872,12],['surgery','Klinik jarrohlik','Townsend','Jarrohlik',1450,4]].map(x=>({id:x[0],title:x[1],author:x[2],subject:x[3],pages:x[4],progress:x[5]}));
const tests=[['phys','Fiziologiya — Yurak-qon tomir tizimi','Fiziologiya',20,20,'O‘rta'],['anat','Anatomiya — Ko‘krak qafasi','Anatomiya',15,15,'O‘rta'],['bio','Biokimyo — Oqsillar almashinuvi','Biokimyo',20,25,'Murakkab']].map(x=>({id:x[0],title:x[1],subject:x[2],questions:x[3],duration:x[4],difficulty:x[5]}));
const qs=[
 ['Yurakning chap qorinchasidan qon qaysi tomirga haydaladi?',['O‘pka arteriyasi','Aorta','Yuqori kovak vena','O‘pka venalari'],1],
 ['Normal kattalarda yurakning tinch holatdagi urish chastotasi qaysi diapazonda?',['20–40/min','40–50/min','60–100/min','120–160/min'],2],
 ['Mitral klapan qaysi bo‘lmalar orasida joylashgan?',['O‘ng bo‘lmacha va o‘ng qorincha','Chap bo‘lmacha va chap qorincha','Qorincha va aorta','Bo‘lmachalar orasida'],1],
 ['Sistolik arterial bosim asosan qaysi fazani aks ettiradi?',['Qorincha sistolasi','Qorincha diastolasi','Bo‘lmacha diastolasi','Izovolumetrik bo‘shashish'],0],
 ['Qaysi tomirlar qon oqimiga eng katta qarshilikni beradi?',['Arteriyalar','Arteriolalar','Venalar','Kapillyarlar'],1],
 ['Frank–Starling qonuni nimani ifodalaydi?',['Yurak urishi va bosim munosabatini','Oldindan yuklanish oshganda zarb hajmi ortishini','Nafas va puls munosabatini','Qon ivishini'],1]
].map(x=>({q:x[0],a:x[1],c:x[2]}));
const chapters=['Kirish va umumiy tushunchalar','Yurak sikli','Qon aylanishining boshqarilishi','Klinik qo‘llanilishi'];
const state={view:localStorage.getItem('medlearn-view')||'dashboard',theme:localStorage.getItem('medlearn-theme')||'light',favs:JSON.parse(localStorage.getItem('medlearn-favs')||'[]'),progress:JSON.parse(localStorage.getItem('medlearn-progress')||'{}'),reader:'guyton',chapter:0,darkReader:false,test:null,index:0,answers:{},seconds:0,timer:null,search:''};
books.forEach(b=>{if(state.progress[b.id]===undefined)state.progress[b.id]=b.progress});
if(!state.favs.length)state.favs=['guyton','lehninger'];
const $=id=>document.getElementById(id), save=()=>{localStorage.setItem('medlearn-view',state.view);localStorage.setItem('medlearn-theme',state.theme);localStorage.setItem('medlearn-favs',JSON.stringify(state.favs));localStorage.setItem('medlearn-progress',JSON.stringify(state.progress))};
function esc(x){return String(x).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function go(v){state.view=v;state.search='';save();render()}
function head(k,t,s=''){return '<div class="page-head"><div><p class="eyebrow">'+k+'</p><h1 class="page-title">'+t+'</h1>'+(s?'<p class="page-subtitle">'+s+'</p>':'')+'</div></div>'}
function nav(){return NAV.map(n=>'<button class="nav-item '+(state.view===n[0]?'active':'')+'" data-view="'+n[0]+'">'+ICONS[n[2]]+'<span>'+n[1]+'</span></button>').join('')}
function bottom(){return NAV.slice(0,5).map(n=>'<button class="'+(state.view===n[0]?'active':'')+'" data-view="'+n[0]+'">'+ICONS[n[2]]+'<span>'+n[1]+'</span></button>').join('')}
function bookCard(b){const p=state.progress[b.id]||0;return '<article class="card book-card"><div class="cover"><span class="cover-tag">'+b.subject+'</span><strong class="cover-title">'+b.title+'</strong><small>'+b.author+'</small></div><div class="book-info"><h3>'+b.title+'</h3><p>'+b.author+' · '+b.pages+' bet</p><div class="book-actions"><button class="btn small primary" data-act="read" data-id="'+b.id+'">'+(p?'Davom etish':'Boshlash')+'</button><button class="btn small heart '+(state.favs.includes(b.id)?'active':'')+'" data-act="fav" data-id="'+b.id+'">'+ICONS.heart+'</button></div><div class="progress" style="margin-top:12px"><i style="width:'+p+'%"></i></div><small class="muted">'+p+'% o‘qilgan</small></div></article>'}
function subjectCard(s){return '<article class="card subject-card"><span class="subject-icon">'+esc(s.name[0])+'</span><h3>'+s.name+'</h3><div class="meta">'+s.materials+' material</div><div class="subject-foot"><div class="progress"><i style="width:'+s.progress+'%"></i></div><small>'+s.progress+'%</small></div><button class="link-btn" data-act="subject" data-id="'+s.id+'">Kursni ochish →</button></article>'}
function testCard(t){return '<article class="card"><p class="eyebrow">'+t.subject+'</p><h3 style="font:800 17px Manrope;margin:0 0 7px">'+t.title+'</h3><p class="muted" style="font-size:13px">'+t.questions+' savol · '+t.duration+' daqiqa · '+t.difficulty+'</p><button class="btn primary" data-act="start" data-id="'+t.id+'">Boshlash '+ICONS.play+'</button></article>'}
const views={
dashboard:()=>head('Xush kelibsiz, Husan','Bugungi o‘qish rejangiz','Kichik, izchil qadamlar katta klinik bilimga olib boradi.')+'<section class="hero"><div><p class="eyebrow" style="color:#8bd4d0">BUGUNGI MAQSAD</p><h2>Fiziologiya bo‘yicha 30 daqiqa</h2><p>Yurak-qon tomir tizimi bo‘limining 64% qismi o‘qilgan. Keyingi mavzu — yurak sikli.</p><div class="progress"><i style="width:72%"></i></div><small style="display:block;margin-top:8px;color:#b9c9cd">22 / 30 daqiqa</small></div><div class="goal-box"><div class="goal-ring"><strong>72%</strong></div><small style="display:block;text-align:center;margin-top:9px;color:#b9c9cd">kunlik maqsad</small></div></section><section class="section grid grid-4">'+[['68%','Umumiy progress','book'],['14','Soat bu oy','test'],['86%','Test aniqligi','test'],['7','Kunlik streak','home']].map(x=>'<article class="card metric"><div><div class="num">'+x[0]+'</div><div class="metric-label">'+x[1]+'</div></div><span class="metric-icon">'+ICONS[x[2]]+'</span></article>').join('')+'</section><section class="section grid grid-2"><article class="card"><div class="section-head"><h2 class="section-title">Davom ettirish</h2><button class="link-btn" data-view="books">Barchasi</button></div><div class="activity-row"><div class="book-cover">PHYSIOLOGY</div><div class="activity-main"><strong>Tibbiy fiziologiya asoslari</strong><small>Yurak sikli · 752 / 1176 bet</small><div class="progress" style="margin-top:9px"><i style="width:64%"></i></div></div><button class="btn small" data-act="read" data-id="guyton">O‘qish</button></div></article><article class="card"><div class="section-head"><h2 class="section-title">Yaqin test</h2><button class="link-btn" data-view="tests">Barchasi</button></div><h3 style="font:800 17px Manrope">Yurak-qon tomir tizimi</h3><p class="muted">20 savol · 20 daqiqa</p><button class="btn primary" data-act="start" data-id="phys">Boshlash</button></article></section>',
subjects:()=>head('Kutubxona','Fanlar','Tibbiyot fanlarini progress bo‘yicha kuzating.')+'<div class="toolbar"><div class="search">'+ICONS.search+'<input id="search" placeholder="Fan qidirish..."></div><select class="select" id="subFilter"><option value="all">Barchasi</option><option value="high">70%+</option><option value="mid">40–69%</option><option value="low">0–39%</option></select></div><div class="grid grid-3" id="subjectGrid">'+subjects.map(subjectCard).join('')+'</div>',
books:()=>head('Kutubxona','Elektron kitoblar','Kitoblarni qidiring, filtrlang va o‘qishni davom ettiring.')+'<div class="toolbar"><div class="search">'+ICONS.search+'<input id="search" placeholder="Kitob, muallif yoki fan..."></div><select class="select" id="bookSort"><option value="recommended">Tavsiya</option><option value="progress">Progress</option><option value="title">Nomi</option></select></div><div class="grid book-grid" id="bookGrid">'+books.map(bookCard).join('')+'</div>',
favorites:()=>{const a=books.filter(b=>state.favs.includes(b.id));return head('Saqlanganlar','Sevimli kitoblar','Tez kirish uchun saqlangan materiallaringiz.')+(a.length?'<div class="grid book-grid">'+a.map(bookCard).join('')+'</div>':'<div class="card empty"><h3>Hali kitob saqlanmagan</h3><p>Kitob kartasidagi yurak tugmasidan foydalaning.</p></div>')},
tests:()=>head('Baholash','Testlar','Bilimingizni qisqa sinovlar bilan tekshiring.')+'<div class="grid grid-3">'+tests.map(testCard).join('')+'</div>',
profile:()=>head('Profil','Husan','Medical student')+'<div class="grid grid-2"><article class="card"><div class="profile-head"><div class="avatar-lg">HS</div><div><h2 style="font:800 22px Manrope;margin:0">Husan</h2><p class="muted">Tibbiyot talabasi</p></div></div><div class="section grid grid-3 compact-mobile"><div><strong>68%</strong><small class="muted" style="display:block">Progress</small></div><div><strong>14</strong><small class="muted" style="display:block">Soat</small></div><div><strong>7</strong><small class="muted" style="display:block">Streak</small></div></div></article><article class="card"><h2 class="section-title">Yutuqlar</h2><div class="badge-row" style="margin-top:15px"><span class="badge">7 kunlik streak</span><span class="badge">10 test</span><span class="badge">Kitobxon</span><span class="badge">Anatomiya 70%+</span></div></article></div><section class="section card"><h2 class="section-title">So‘nggi natijalar</h2><div class="activity-row"><div class="activity-main"><strong>Fiziologiya — Yurak-qon tomir tizimi</strong><small>17 / 20 · 85%</small></div><span class="badge">85%</span></div></section>',
settings:()=>head('Profil','Sozlamalar','Ilova ko‘rinishi va o‘qish tajribasini moslang.')+'<article class="card">'+row('Tungi mavzu','Qorong‘i interfeys',state.theme==='dark','theme')+row('Bildirishnomalar','Test va o‘qish eslatmalari',true,'notify')+row('Katta shrift','O‘qishda kattaroq matn',false,'font')+'<div class="setting-row"><div><strong>Til</strong><small>Interfeys tili</small></div><select class="select" id="lang"><option>O‘zbekcha</option><option>Русский</option><option>English</option></select></div></article>',
detailSubject:()=>{const s=subjects.find(x=>x.id===state.detail)||subjects[0];return head('Fan',s.name,s.materials+' ta o‘quv materiali')+'<div class="grid grid-2"><article class="card"><h2 class="section-title">Kurs progressi</h2><div class="metric" style="margin-top:18px"><div class="num">'+s.progress+'%</div><span class="badge">'+s.materials+' material</span></div><div class="progress" style="margin-top:14px"><i style="width:'+s.progress+'%"></i></div></article><article class="card"><h2 class="section-title">Mavzular</h2><div class="chapter-list" style="margin-top:12px">'+chapters.map((c,i)=>'<button class="chapter" data-act="reader" data-id="guyton" data-ch="'+i+'"><strong>'+c+'</strong><span>'+((i+1)*18)+'%</span></button>').join('')+'</div></article></div>'},
bookDetail:()=>{const b=books.find(x=>x.id===state.reader)||books[0];return head('Elektron kitob',b.title,b.author+' · '+b.pages+' bet')+'<div class="book-detail"><div class="large-cover"><span class="cover-tag">'+b.subject+'</span><strong class="cover-title">'+b.title+'</strong><small>'+b.author+'</small></div><div><div class="detail-meta"><span>'+b.pages+' bet</span><span>'+state.progress[b.id]+'% o‘qilgan</span></div><h2 style="margin-top:18px">Mundarija</h2><div class="chapter-list">'+chapters.map((c,i)=>'<button class="chapter" data-act="reader" data-id="'+b.id+'" data-ch="'+i+'"><strong>'+c+'</strong><span>›</span></button>').join('')+'</div><button class="btn primary" style="margin-top:16px" data-act="reader" data-id="'+b.id+'" data-ch="'+Math.min(3,Math.floor((state.progress[b.id]||0)/25))+'">O‘qishni davom ettirish</button></div></div>'},
reader:()=>{const b=books.find(x=>x.id===state.reader)||books[0];const c=chapters[state.chapter];return '<div class="reader"><div class="reader-head"><button class="btn small" data-view="bookDetail">'+ICONS.back+' Kitob</button><div><button class="btn small" data-act="rtheme">'+(state.darkReader?'Yorug‘':'Qorong‘i')+'</button> <button class="btn small" data-act="fontDown">A−</button> <button class="btn small" data-act="fontUp">A+</button></div></div><div class="reader-layout '+(state.darkReader?'reader-dark':'')+'"><aside class="reader-side card"><h3 class="section-title">'+b.title+'</h3><div class="chapter-list" style="margin-top:12px">'+chapters.map((x,i)=>'<button class="chapter" data-act="rchapter" data-ch="'+i+'"><strong>'+((i+1)+'. '+x)+'</strong></button>').join('')+'</div></aside><article class="reader-text" id="readerText"><p class="eyebrow">'+b.subject+'</p><h2>'+c+'</h2><p>Bu demo o‘quv matni MedLearn elektron kitob o‘quvchisini namoyish qiladi. Mavzuni o‘qish jarayonida bo‘limlar o‘rtasida harakatlanish, shriftni o‘zgartirish va o‘qish rejimini almashtirish mumkin.</p><h3>Asosiy tushuncha</h3><p>Yurak sikli davomida sistola va diastola ketma-ketligi qonning yurak bo‘limlari hamda tomirlarda harakatini ta’minlaydi. Klinik fikrlashda normal fiziologik mexanizmlarni tushunish keyingi patologik o‘zgarishlarni izohlashga yordam beradi.</p><h3>O‘rganish uchun</h3><p>Ta’riflarni yodlash bilan cheklanmasdan, sabab–oqibat bog‘lanishlarini yozib chiqing va mavzuni test savollari orqali tekshiring.</p><div class="test-controls"><button class="btn" data-act="rprev">← Oldingi</button><button class="btn primary" data-act="rnext">Keyingi →</button></div></article></div></div>'},
testInterface:()=>{const t=state.test||tests[0],q=qs[state.index%qs.length];return head('Test',t.title,'Savol '+(state.index+1)+' / '+t.questions)+'<div class="test-layout"><article class="card question-card"><div class="timer" id="timer">'+fmt(state.seconds)+'</div><h2>'+q.q+'</h2>'+q.a.map((a,i)=>'<button class="option '+(state.answers[state.index]===i?'selected':'')+'" data-act="answer" data-answer="'+i+'"><span class="option-key">'+String.fromCharCode(65+i)+'</span>'+a+'</button>').join('')+'<div class="test-controls">'+(state.index?'<button class="btn" data-act="prev">← Oldingi</button>':'<span></span>')+'<button class="btn primary" data-act="next">'+(state.index===t.questions-1?'Yakunlash':'Keyingi')+'</button></div></article><aside class="card test-sidebar"><h2 class="section-title">Savollar</h2><div class="test-nav" style="margin-top:14px">'+Array.from({length:Math.min(t.questions,20)},(_,i)=>'<button class="q-dot '+(i===state.index?'current ':'')+(state.answers[i]!==undefined?'done':'')+'" data-act="jump" data-index="'+i+'">'+(i+1)+'</button>').join('')+'</div><button class="btn danger" style="width:100%;justify-content:center;margin-top:18px" data-act="finish">Testni tugatish</button></aside></div>'},
results:()=>{const r=state.result||{correct:4,incorrect:1,unanswered:1,total:6,seconds:300},p=Math.round(r.correct/r.total*100);return head('Natija','Test yakunlandi','Natijangiz saqlandi.')+'<div class="result-grid"><article class="card score-card"><div class="score-ring" style="--score:'+p*3.6+'deg"><span>'+p+'%</span></div><h2 style="font:800 20px Manrope">Natija</h2><p class="muted">'+r.correct+' ta to‘g‘ri, '+r.incorrect+' ta noto‘g‘ri, '+r.unanswered+' ta javobsiz.</p><button class="btn primary" data-view="tests">Testlarga qaytish</button></article><article class="card"><h2 class="section-title">Tahlil</h2><div class="bar-row"><span>To‘g‘ri</span><div class="bar"><i style="width:'+(r.correct/r.total*100)+'%"></i></div><b>'+r.correct+'</b></div><div class="bar-row"><span>Noto‘g‘ri</span><div class="bar"><i style="width:'+(r.incorrect/r.total*100)+'%"></i></div><b>'+r.incorrect+'</b></div><div class="bar-row"><span>Javobsiz</span><div class="bar"><i style="width:'+(r.unanswered/r.total*100)+'%"></i></div><b>'+r.unanswered+'</b></div><p class="muted">Sarflangan vaqt: '+fmt(r.seconds)+'</p></article></div>'}
};
function row(a,b,on,key){return '<div class="setting-row"><div><strong>'+a+'</strong><small>'+b+'</small></div><button class="switch '+(on?'on':'')+'" data-act="setting" data-key="'+key+'"><i></i></button></div>'}
function fmt(s){return Math.floor(s/60).toString().padStart(2,'0')+':'+(s%60).toString().padStart(2,'0')}
function render(){document.documentElement.dataset.theme=state.theme;$('desktopNav').innerHTML=nav();$('bottomNav').innerHTML=bottom();$('topbarTitle').textContent=NAV.find(x=>x[0]===state.view)?.[1]||'MedLearn';$('themeToggle').innerHTML=state.theme==='dark'?ICONS.sun:ICONS.moon;$('viewRoot').innerHTML=views[state.view]?views[state.view]():views.dashboard();bind();save()}
function bind(){document.querySelectorAll('[data-view]').forEach(x=>x.onclick=()=>go(x.dataset.view));document.querySelectorAll('[data-act]').forEach(x=>x.onclick=()=>act(x.dataset.act,x));$('themeToggle').onclick=()=>{state.theme=state.theme==='dark'?'light':'dark';render()};$('mobileMenu')?.addEventListener('click',()=>openModal('Navigatsiya','<div class="side-nav" style="display:grid">'+nav()+'</div>'));$('notificationBtn')?.addEventListener('click',()=>openModal('Bildirishnomalar','<p class="muted">Bugun 19:00 da Fiziologiya testi rejalashtirilgan.</p>'));const s=$('search');if(s)s.oninput=e=>{state.search=e.target.value.toLowerCase();if(state.view==='subjects')filterSubjects();else filterBooks()};$('subFilter')?.addEventListener('change',filterSubjects);$('bookSort')?.addEventListener('change',filterBooks)}
function filterSubjects(){const q=state.search,f=$('subFilter')?.value||'all';const a=subjects.filter(s=>s.name.toLowerCase().includes(q)).filter(s=>f==='all'||f==='high'&&s.progress>=70||f==='mid'&&s.progress>=40&&s.progress<70||f==='low'&&s.progress<40);$('subjectGrid').innerHTML=a.map(subjectCard).join('')||'<div class="card empty"><h3>Fan topilmadi</h3></div>';bind()}
function filterBooks(){const q=state.search,sort=$('bookSort')?.value||'recommended';let a=books.filter(b=>(b.title+' '+b.author+' '+b.subject).toLowerCase().includes(q));if(sort==='progress')a.sort((x,y)=>(state.progress[y.id]||0)-(state.progress[x.id]||0));if(sort==='title')a.sort((x,y)=>x.title.localeCompare(y.title));$('bookGrid').innerHTML=a.map(bookCard).join('')||'<div class="card empty"><h3>Kitob topilmadi</h3></div>';bind()}
function act(a,x){if(a==='fav'){const id=x.dataset.id;state.favs=state.favs.includes(id)?state.favs.filter(v=>v!==id):[...state.favs,id];const initialModal=$('modalBackdrop');if(initialModal){initialModal.hidden=true;initialModal.style.setProperty('display','none','important')}render();return}if(a==='read'){state.reader=x.dataset.id;state.view='bookDetail';render();return}if(a==='reader'){state.reader=x.dataset.id;state.chapter=+x.dataset.ch;state.view='reader';render();return}if(a==='subject'){state.detail=x.dataset.id;state.view='detailSubject';render();return}if(a==='start'){state.test=tests.find(t=>t.id===x.dataset.id)||tests[0];state.index=0;state.answers={};state.seconds=state.test.duration*60;state.view='testInterface';startTimer();render();return}if(a==='answer'){state.answers[state.index]=+x.dataset.answer;render();return}if(a==='next'){if(state.index>=state.test.questions-1){finish();return}state.index++;render();return}if(a==='prev'){state.index=Math.max(0,state.index-1);render();return}if(a==='jump'){state.index=+x.dataset.index;render();return}if(a==='finish'){finish();return}if(a==='rchapter'){state.chapter=+x.dataset.ch;render();return}if(a==='rprev'){state.chapter=Math.max(0,state.chapter-1);render();return}if(a==='rnext'){if(state.chapter<chapters.length-1)state.chapter++;else state.progress[state.reader]=Math.min(100,(state.progress[state.reader]||0)+10);render();return}if(a==='rtheme'){state.darkReader=!state.darkReader;render();return}if(a==='fontDown'||a==='fontUp'){const r=$('readerText');if(r)r.style.fontSize=Math.max(14,Math.min(24,parseFloat(getComputedStyle(r).fontSize)+(a==='fontUp'?1:-1)))+'px';return}if(a==='setting'){if(x.dataset.key==='theme'){state.theme=state.theme==='dark'?'light':'dark';render()}else{x.classList.toggle('on')}}}
function startTimer(){clearInterval(state.timer);state.timer=setInterval(()=>{state.seconds--;if($('timer'))$('timer').textContent=fmt(state.seconds);if(state.seconds<=0)finish()},1000)}
function finish(){clearInterval(state.timer);const total=state.test?.questions||6;let correct=0;for(let i=0;i<total;i++)if(state.answers[i]===qs[i%qs.length].c)correct++;const answered=Object.keys(state.answers).length;state.result={correct,incorrect:answered-correct,unanswered:total-answered,total,seconds:(state.test.duration*60)-state.seconds};state.view='results';render()}
function openModal(title,body){const b=$('modalBackdrop');$('modalTitle').textContent=title;$('modalBody').innerHTML=body;b.hidden=false;b.style.removeProperty('display');$('modalClose').onclick=()=>{b.hidden=true;b.style.setProperty('display','none','important')};b.onclick=e=>{if(e.target===b){b.hidden=true;b.style.setProperty('display','none','important')}};document.querySelectorAll('#modalBody [data-view]').forEach(x=>x.onclick=()=>{b.hidden=true;b.style.setProperty('display','none','important');go(x.dataset.view)})}
render();